services:
  app:
    build: .
    container_name: bookland
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DATA_PATH=/data
      - BOOKS_PATH=/books
      - STATIC_PATH=/app/static
      - PORT=8080
    volumes:
      - ./backend/data:/data
      - ~/Downloads:/books:ro
