services:
  app:
    build: .
    container_name: bookland
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATA_PATH=/data
      - BOOKS_PATH=/books
      - STATIC_PATH=/app/static
    volumes:
      - ./data:/data
      - ${BOOKS_PATH}:/books:ro
